version: '2'
services:
  web:
    build: .
    command: bash -c " pip install -r requirements.txt && python ./src/manage.py db stamp head &&python ./src/manage.py db migrate && python ./src/manage.py db upgrade && python ./src/app.py"
    image: swapnil085/devops:backend_image
    container_name: backend-parking
    volumes:
     - .:/src
    ports:
     - "5000:5000"
    links:
     - db
    hostname: localhost
  db:
    container_name: parking_database
    hostname: localhost
    image: swapnil085/devops:mysql_image
    ports:
      - "32000:3306"
    environment:
       MYSQL_ROOT_PASSWORD: 123456
       MYSQL_PASSWORD: 123456
       MYSQL_DATABASE: parking

