"""empty message

Revision ID: 2294afc1e6d0
Revises: e4cef741a14c
Create Date: 2018-11-21 23:07:13.849857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2294afc1e6d0'
down_revision = 'e4cef741a14c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('walkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('reservation_no', sa.String(length=255), nullable=False),
    sa.Column('car_no', sa.String(length=255), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('walkins')
    # ### end Alembic commands ###
