"""empty message

Revision ID: 2d0df2fc0694
Revises: 5450b878e1e4
Create Date: 2018-11-19 20:49:19.986057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d0df2fc0694'
down_revision = '5450b878e1e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['id'])
    op.add_column('slots', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slots', 'date')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'user_id')
    # ### end Alembic commands ###
