"""empty message

Revision ID: 2e2621e4c820
Revises: 49a3d9448137
Create Date: 2018-11-18 11:56:55.946562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e2621e4c820'
down_revision = '49a3d9448137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('comments', sa.String(length=255), nullable=True))
    op.drop_column('feedbacks', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('description', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('feedbacks', 'comments')
    # ### end Alembic commands ###
